# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireNetworkActivityLogger', '~> 2.3'


  # Pods for iOS-app

end
